# Generated by Django 5.2.17 on 2026-09-07 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_follow_postread'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
