# Generated by Django 5.2.17 on 2026-09-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_reaction_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
